### ISSUE TITLE
Enhance control protocol to support overriding default property values

### ISSUE THREAD

**Issue by jfallows** [k3po/specification.k3po.control#1]
Required by kaazing/robot#52.

**Comment by jfallows** [comment]
Agreed.

**Comment by jfallows** [comment]
The intent of this overridable properties enhancement is part of handling the re-targeting of logical and physical transports.

For example, suppose we had a set of AMQP 1.0 specification scripts authored using tcp://localhost:5672 and wanted to use them to test AMQP 1.0 in a browser over WebSocket.

This would benefit from syntax similar to the following:
`alias tcp://localhost:5672 ws://localhost:8080/amqp`

Similarly, we should probably be using `example.com` to author these scripts instead of  `localhost` and a similar aliasing mechanism would be:
`alias dns://example.com dns://localhost`, OR
`alias dns://example.com ip://127.0.0.1`

We need to be careful about going too far with parameterizing scripts with properties, otherwise we pretty soon have scripts that _require_ coordination on their exposed properties when configured externally just to get the scripts to work.

**Comment by jfallows** [comment]
Logical DNS resolution would probably require a `NameResolver` abstraction at in `TcpBootstrapFactorySpi`.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#154
